language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
install: true
before_install:
  - export JAVA_OPTS="-Xms1024m -Xmx1024m"
before_script:
  - chmod +x gradlew
script: ./gradlew --no-daemon
